# Generated by Django 4.2.3 on 2023-07-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_author_remove_profile_user'),
        ('blog', '0005_article_created_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='account.author'),
        ),
    ]
