# Generated by Django 4.2.3 on 2023-07-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
