# Generated by Django 4.2.3 on 2023-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('image', models.ImageField(upload_to='images/Authors')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('slug', models.CharField(editable=False, max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
