# Generated by Django 4.2.3 on 2023-07-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_profile_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.FileField(upload_to='images/Authors'),
        ),
    ]
